### ISSUE TITLE
Cucumber doesn't work

### ISSUE THREAD

**Issue by Damian1234523** [Damian1234523/Cheetah#3]
Cucumber + Selenium won't run.
Cucumber without selenium seems to work.
I tried the documented way to install it. The App wasn't able to start at all.
After dropping the selenium files manually at least the syntax highlighting started working.
We should consider using an alternative to selenium. An other option would be to simply use Rails own testenvirnoment which is probably less bitchy.

**Comment by Damian1234523** [comment]
Problem is caused by incompatible JSON gem. No Solutuion found so far.

**Comment by LiorEnergy** [comment]
Cucumber won't work. we give up.
